const bootAmbientAudio = () => {
  if (typeof window === 'undefined' || typeof document === 'undefined') return;
  let enabled = localStorage.getItem('mini_ambient_sound') !== 'off';
  let started = false, starting = false;
  let ctx: AudioContext | null = null;
  let master: GainNode | null = null;
  let scheduler: number | null = null;
  const control = document.createElement('button');
  control.type = 'button';
  control.className = 'ambient-sound-control';
  control.setAttribute('aria-label', 'Ativar ou pausar música relaxante');
  Object.assign(control.style,{position:'fixed',right:'14px',bottom:'14px',zIndex:'1000',minHeight:'40px',padding:'8px 13px',borderRadius:'999px',border:'1px solid rgba(111,47,105,.24)',background:'rgba(255,250,240,.96)',color:'#5b2858',boxShadow:'0 8px 24px rgba(75,55,45,.12)',backdropFilter:'blur(10px)',fontSize:'.74rem',fontWeight:'700',cursor:'pointer'});
  const placeControl=()=>{const result=!!document.querySelector('.report-card[data-approved="1"]');control.style.display=result?'none':'';const mobile=window.matchMedia('(max-width:700px)').matches;const landing=!!document.querySelector('.landing-v2');control.style.position=mobile&&landing?'absolute':'fixed';control.style.right=mobile&&landing?'18px':'14px';control.style.bottom=mobile&&landing?'18px':'14px'};
  const volumeForScreen=()=>document.querySelector('.payment-card')?0.055:0.11;
  const update=()=>{control.textContent=started?'♪ Som: ligado':'♪ Ativar som';control.setAttribute('aria-pressed',String(started));placeControl()};
  const playTone=(frequency:number,when:number,duration:number,gain:number)=>{if(!ctx||!master)return;const osc=ctx.createOscillator(),g=ctx.createGain(),filter=ctx.createBiquadFilter();osc.type='sine';osc.frequency.setValueAtTime(frequency,when);filter.type='lowpass';filter.frequency.value=1200;g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(gain,when+.22);g.gain.exponentialRampToValueAtTime(.0001,when+duration);osc.connect(filter);filter.connect(g);g.connect(master);osc.start(when);osc.stop(when+duration+.2)};
  const schedulePhrase=()=>{if(!ctx||!started)return;const now=ctx.currentTime+.05;[220,261.63,196,246.94].forEach((root,i)=>{const t=now+i*6.8;playTone(root,t,8.2,.016);playTone(root*1.5,t+.25,7.6,.011);playTone(root*2,t+1.3,4.3,.018);playTone(root*2.5,t+3.9,3.8,.012)})};
  const start=async()=>{if(!enabled||started||starting)return;starting=true;try{const Ctor=window.AudioContext||(window as any).webkitAudioContext;if(!Ctor)throw new Error('AudioContext unavailable');ctx=new Ctor();master=ctx.createGain();master.gain.value=volumeForScreen();master.connect(ctx.destination);await ctx.resume();started=ctx.state==='running';if(!started)throw new Error('AudioContext blocked');schedulePhrase();scheduler=window.setInterval(schedulePhrase,27200)}catch(error){console.warn('Ambient audio could not start:',error);started=false;if(ctx){try{await ctx.close()}catch{}}ctx=null;master=null}finally{starting=false;update()}};
  const stop=async()=>{started=false;if(scheduler!==null)window.clearInterval(scheduler);scheduler=null;if(ctx){try{await ctx.close()}catch{}}ctx=null;master=null;update()};
  const syncForScreen=()=>{if(ctx&&master&&ctx.state==='running')master.gain.setTargetAtTime(volumeForScreen(),ctx.currentTime,.8);placeControl()};
  control.addEventListener('click',async event=>{event.preventDefault();event.stopPropagation();if(started){enabled=false;localStorage.setItem('mini_ambient_sound','off');await stop()}else{enabled=true;localStorage.setItem('mini_ambient_sound','on');await start()}});
  const startOnFirstInteraction=()=>{if(!enabled||started)return;void start()};
  document.addEventListener('pointerdown',startOnFirstInteraction,{once:true,passive:true});document.addEventListener('keydown',startOnFirstInteraction,{once:true});window.addEventListener('resize',placeControl,{passive:true});
  new MutationObserver(syncForScreen).observe(document.documentElement,{childList:true,subtree:true});document.body.appendChild(control);update();
};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootAmbientAudio,{once:true});else bootAmbientAudio();
