import { createHmac, timingSafeEqual } from 'node:crypto';
type Req = { method?: string; query: Record<string, string | string[] | undefined> };
type Res = { status: (code: number) => Res; setHeader: (name: string, value: string) => void; end: (body?: any) => void; json: (data: unknown) => void };
const clean=(v?:string)=>(v||'').trim().replace(/^["'](.*)["']$/,'$1').trim();
const DB_URL=clean(process.env.SUPABASE_URL).replace(/\/$/,'');
const DB_KEY=[process.env.SUPABASE_SERVICE_ROLE_KEY,process.env.SUPABASE_SECRET_KEY].map(clean).find(k=>Boolean(k)&&!k.startsWith('sb_publishable_'))||'';
const SECRET=clean(process.env.RESULT_TOKEN_SECRET);
const validId=(id:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id);
function validToken(id:string,token:string){if(SECRET.length<32||!token)return false;const a=Buffer.from(createHmac('sha256',SECRET).update(`result:${id}`).digest('base64url'));const b=Buffer.from(token);return a.length===b.length&&timingSafeEqual(a,b)}
async function db(resource:string){if(!DB_URL||!DB_KEY)throw new Error('DB_CONFIG');const r=await fetch(`${DB_URL}/rest/v1/${resource}`,{headers:{apikey:DB_KEY,...(DB_KEY.startsWith('eyJ')?{Authorization:`Bearer ${DB_KEY}`}:{})}});if(!r.ok)throw new Error(`DB_${r.status}`);return await r.json()}
const esc=(v:unknown)=>String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
function makePdf(lines:string[]){const content=['BT','/F1 22 Tf','50 785 Td','(JANAINA ARAUJO) Tj','/F1 11 Tf','0 -20 Td','(TERAPEUTA INTEGRATIVA) Tj','/F1 18 Tf','0 -55 Td','(SEU RELATORIO PERSONALIZADO) Tj','/F1 11 Tf',...lines.flatMap(x=>['0 -27 Td',`(${esc(x)}) Tj`]),'ET'].join('\n');const objs=[`<< /Type /Catalog /Pages 2 0 R >>`,`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,`<< /Length ${Buffer.byteLength(content,'latin1')} >>\nstream\n${content}\nendstream`];let out='%PDF-1.4\n';const offsets=[0];objs.forEach((o,i)=>{offsets[i+1]=Buffer.byteLength(out,'latin1');out+=`${i+1} 0 obj\n${o}\nendobj\n`});const x=Buffer.byteLength(out,'latin1');out+=`xref\n0 6\n0000000000 65535 f \n`;for(let i=1;i<=5;i++)out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return Buffer.from(out,'latin1')}
function summary(d:string){if(d==='INSEGURANÇA')return 'Observe como duvidas e autocobranca podem influenciar suas decisoes.';if(d==='PROCRASTINAÇÃO')return 'Observe como adiamentos e urgencia podem influenciar suas escolhas.';return 'Observe como receios e antecipacao de consequencias podem influenciar suas decisoes.'}
export default async function handler(req:Req,res:Res){if(req.method!=='GET')return res.status(405).json({error:'Método não permitido.'});try{const id=String(req.query.id||''),token=String(req.query.token||'');if(!validId(id))return res.status(400).json({error:'Sessão inválida.'});if(!validToken(id,token))return res.status(403).json({error:'Acesso ao PDF não autorizado.'});const rows=await db(`quiz_sessions?quiz_session_id=eq.${encodeURIComponent(id)}&select=quiz_session_id,nome,score_medo,score_inseguranca,score_procrastinacao,resultado_dominante,payment_status,paid_at`);const q=rows?.[0];if(!q)return res.status(404).json({error:'Diagnóstico não encontrado.'});if(q.payment_status!=='paid')return res.status(402).json({error:'Pagamento ainda não confirmado.'});const d=String(q.resultado_dominante||'MEDO');const pdf=makePdf([`Ola, ${String(q.nome||'Cliente')}.`,`Principal area de atencao: ${d}`,`Medo: ${q.score_medo}/12`,`Inseguranca: ${q.score_inseguranca}/12`,`Procrastinacao: ${q.score_procrastinacao}/12`,'',summary(d),'','Pagamento confirmado.','Este material apoia o autoconhecimento e nao substitui avaliacao profissional.']);res.status(200);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="mini-diagnostico-${id.slice(0,8)}.pdf"`);res.setHeader('Cache-Control','private, no-store');return res.end(pdf)}catch(e){console.error('PDF diagnosis error',e);return res.status(500).json({error:'Não foi possível gerar o diagnóstico em PDF.'})}}
